"""empty message

Revision ID: 2b4638fc8ad1
Revises: 19492ee2b186
Create Date: 2023-09-15 07:34:16.988830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b4638fc8ad1'
down_revision = '19492ee2b186'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=20), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
