"""empty message

Revision ID: 5f14cbfc67e5
Revises: 2339ab8bd2aa
Create Date: 2023-08-18 10:31:09.185172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f14cbfc67e5'
down_revision = '2339ab8bd2aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('provincia_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'provincias', ['provincia_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('provincia_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
