"""empty message

Revision ID: 73315f763525
Revises: b584cc825319
Create Date: 2023-08-25 02:15:46.916920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73315f763525'
down_revision = 'b584cc825319'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_productor',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('productor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['productor_id'], ['perfil_productores.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_productor')
    # ### end Alembic commands ###
