"""empty message

Revision ID: 75de66fb87bf
Revises: e806e8232fad
Create Date: 2023-08-19 20:24:09.633728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75de66fb87bf'
down_revision = 'e806e8232fad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('direccion', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.Integer(), nullable=False),
    sa.Column('codigo_postal', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('comunidad_autonoma_id', sa.Integer(), nullable=False),
    sa.Column('provincia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comunidad_autonoma_id'], ['comunidades_autonomas.id'], ),
    sa.ForeignKeyConstraint(['provincia_id'], ['provincias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefono')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('apellido', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('direccion', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('telefono', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('codigo_postal', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comunidad_autonoma_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('provincia_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['comunidad_autonoma_id'], ['comunidades_autonomas.id'], name='user_comunidad_autonoma_id_fkey'),
    sa.ForeignKeyConstraint(['provincia_id'], ['provincias.id'], name='user_provincia_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key'),
    sa.UniqueConstraint('telefono', name='user_telefono_key')
    )
    op.drop_table('users')
    # ### end Alembic commands ###
