"""empty message

Revision ID: 91e635513343
Revises: c96609945d76
Create Date: 2023-09-07 10:33:46.461444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91e635513343'
down_revision = 'c96609945d76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfil_productores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('municipio', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfil_productores', schema=None) as batch_op:
        batch_op.drop_column('municipio')

    # ### end Alembic commands ###
