"""empty message

Revision ID: b584cc825319
Revises: fe5e9eca94ee
Create Date: 2023-08-25 01:45:41.319170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b584cc825319'
down_revision = 'fe5e9eca94ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_produccion', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('recogida', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('recogida')
        batch_op.drop_column('tipo_produccion')

    # ### end Alembic commands ###
