"""empty message

Revision ID: b5eaa2dbef2f
Revises: 49fdc585b56a
Create Date: 2023-09-25 14:49:27.246170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5eaa2dbef2f'
down_revision = '49fdc585b56a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perfil_productores_nombre_huerta', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favoritos_perfil_productores_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'perfil_productores', ['perfil_productores_nombre_huerta'], ['nombre_huerta'])
        batch_op.drop_column('perfil_productores_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perfil_productores_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favoritos_perfil_productores_id_fkey', 'perfil_productores', ['perfil_productores_id'], ['id'])
        batch_op.drop_column('perfil_productores_nombre_huerta')

    # ### end Alembic commands ###
