"""empty message

Revision ID: b7e3a6387e47
Revises: ef9847ea79a2
Create Date: 2023-08-27 22:21:13.813712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7e3a6387e47'
down_revision = 'ef9847ea79a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfil_productores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comunidad_autonoma', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('provincia', sa.String(length=80), nullable=True))
        batch_op.drop_column('comunidad_autonoma_id')
        batch_op.drop_column('provincia_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfil_productores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provincia_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('comunidad_autonoma_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_column('provincia')
        batch_op.drop_column('comunidad_autonoma')

    # ### end Alembic commands ###
