"""empty message

Revision ID: c9dff75e5441
Revises: caf04d758289
Create Date: 2023-08-25 03:00:04.033179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9dff75e5441'
down_revision = 'caf04d758289'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lista_producto',
    sa.Column('lista_id', sa.Integer(), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lista_id'], ['listas.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lista_producto')
    # ### end Alembic commands ###
