"""empty message

Revision ID: d31979cd7cf4
Revises: ea3051a44340
Create Date: 2023-08-19 01:49:26.231056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd31979cd7cf4'
down_revision = 'ea3051a44340'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comunidades_autonomas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provincias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('comunidad_autonoma_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comunidad_autonoma_id'], ['comunidades_autonomas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('apellido', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('direccion', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('telefono', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('codigo_postal', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('comunidad_autonoma_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('provincia_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['telefono'])
        batch_op.create_foreign_key(None, 'provincias', ['provincia_id'], ['id'])
        batch_op.create_foreign_key(None, 'comunidades_autonomas', ['comunidad_autonoma_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('provincia_id')
        batch_op.drop_column('comunidad_autonoma_id')
        batch_op.drop_column('codigo_postal')
        batch_op.drop_column('telefono')
        batch_op.drop_column('direccion')
        batch_op.drop_column('apellido')
        batch_op.drop_column('nombre')

    op.drop_table('provincias')
    op.drop_table('comunidades_autonomas')
    # ### end Alembic commands ###
