"""empty message

Revision ID: e806e8232fad
Revises: d31979cd7cf4
Create Date: 2023-08-19 02:24:31.301298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e806e8232fad'
down_revision = 'd31979cd7cf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perfil_productores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_huerta', sa.String(length=250), nullable=True),
    sa.Column('foto_portada', sa.String(length=250), nullable=True),
    sa.Column('foto_perfil', sa.String(length=250), nullable=True),
    sa.Column('problemas', sa.String(length=250), nullable=True),
    sa.Column('donde_encontrar', sa.String(length=250), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('productor_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=True),
    sa.Column('variedad', sa.String(length=250), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('unidad_medida', sa.String(length=250), nullable=True),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['productor_id'], ['perfil_productores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productos')
    op.drop_table('perfil_productores')
    # ### end Alembic commands ###
