"""empty message

Revision ID: fe6ad999a552
Revises: 97f7d2ba5cb7
Create Date: 2023-08-25 10:43:01.480285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe6ad999a552'
down_revision = '97f7d2ba5cb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedido_producto')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedido_producto',
    sa.Column('pedido_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('producto_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], name='pedido_producto_pedido_id_fkey'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name='pedido_producto_producto_id_fkey')
    )
    # ### end Alembic commands ###
